[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn wsgi:application --bind 0.0.0.0:"
healthCheckPath = "/"
healthCheckTimeout = 300

[[services]]
name = "masonite-hola-mundo"
type = "web"

[[services.ports]]
port = 8000
